//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryContentComment
    {
        public int Id { get; set; }
        public string Comments { get; set; }
        public Nullable<int> ContentId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public string UserType { get; set; }
    
        public virtual CategoryContent CategoryContent { get; set; }
        public virtual User User { get; set; }
    }
}
