//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.CategoryContents = new HashSet<CategoryContent>();
            this.PresenterCategories = new HashSet<PresenterCategory>();
            this.ParticipantCategories = new HashSet<ParticipantCategory>();
        }
    
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ChannelNo { get; set; }
        public Nullable<bool> IsFree { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
    
        public virtual ICollection<CategoryContent> CategoryContents { get; set; }
        public virtual ICollection<PresenterCategory> PresenterCategories { get; set; }
        public virtual ICollection<ParticipantCategory> ParticipantCategories { get; set; }
    }
}
