//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryContent
    {
        public CategoryContent()
        {
            this.CategoryContentComments = new HashSet<CategoryContentComment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ImageName { get; set; }
        public string VideoName { get; set; }
        public string VideoFrom { get; set; }
    
        public virtual ICollection<CategoryContentComment> CategoryContentComments { get; set; }
        public virtual Category Category { get; set; }
    }
}
