//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresenterCategory
    {
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
