//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliverLoad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcceptedLoadOffer
    {
        public long Id { get; set; }
        public int LoadId { get; set; }
        public int LoadOwnerId { get; set; }
        public int VehicleOwnerId { get; set; }
        public System.DateTime AcceptedDate { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> ModifiedAcceptedDate { get; set; }
        public Nullable<bool> IsAcceptedByLoadOwner { get; set; }
        public Nullable<System.DateTime> LoadOwnerAcceptedDate { get; set; }
    
        public virtual OverloadCategory OverloadCategory { get; set; }
    }
}
