//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CCCEntities : DbContext
    {
        public CCCEntities()
            : base("name=CCCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CategoryContent> CategoryContents { get; set; }
        public DbSet<PresenterCategory> PresenterCategories { get; set; }
        public DbSet<CategoryContentComment> CategoryContentComments { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<PaymentHistory> PaymentHistories { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Subscription> Subscriptions { get; set; }
        public DbSet<ParticipantCategory> ParticipantCategories { get; set; }
    }
}
