//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliverLoad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelRequestMaster
    {
        public long ID { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ChannelId { get; set; }
        public string RequestComment { get; set; }
        public string RequestStatus { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> ResponceDate { get; set; }
        public string ResponceComment { get; set; }
        public Nullable<int> RespondedBy { get; set; }
        public Nullable<int> RequestedBy { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
