//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliverLoad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMonitory
    {
        public long Id { get; set; }
        public int UserId { get; set; }
        public Nullable<decimal> TotalBalance { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isCouponCodeApplied { get; set; }
        public string CouponCode { get; set; }
    }
}
