//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliverLoad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackingInformation
    {
        public int TRA_Id { get; set; }
        public string Tracking_Code { get; set; }
        public Nullable<decimal> StartingLatitude { get; set; }
        public Nullable<decimal> StartingLongitude { get; set; }
        public decimal CurrentLatitude { get; set; }
        public decimal CurrentLongitude { get; set; }
        public Nullable<decimal> EndingLatitude { get; set; }
        public Nullable<decimal> EndingLongitude { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
